### ISSUE TITLE
IsardVDI not working on Fedora30

### ISSUE THREAD

**Issue by samuak8** [isard-vdi/isard#154]
Hi, we are trying to run IsardVDI on Fedora30 which was realeased few days ago, and it's not working, we run as usual the docker but we aren't able to open it on any web browser, we tried to disable the firewall but neither works, and it fails when you try to run the docker.

If you guys know what going wrong with the docker in Fedora30, let us know about, we are really interested. In fedora29 work perfectly.

Thanks for paying atenttion!

**Comment by jvinolas** [comment]
How did you install docker in Fedora 30? This seems to be the root cause of this problem we also faced. Do not install it with moby-engine. Add Fedora29 docker repo and add it from that repo:

- sudo dnf config-manager     --add-repo     https://download.docker.com/linux/fedora/docker-ce.repo
- sudo dnf install --releasever=29 docker-ce docker-ce-cli containerd.io

**Comment by sim6** [comment]
We cannot help you without more information, please add more comments to the issue if you would like to have more support.
