### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by antecessor** [isard-vdi/isard#214]
Every time I close the browser window and want to open again I will face these errors in logs.
```
Database isard not found!
2020/06/11 22:03:16 - WIZARD - ERROR: If you need to recreate isard database you should activate wizard again:
2020/06/11 22:03:16 - WIZARD - ERROR:    REMOVE /opt/isard/database/wizard/wizard-disabled file  (rm /opt/isard/database/wizard/wizard-disabled) and start isard again
```

Then, I will remove wizard-disabled and set everything again, but these error will occur next time. I have installed the docker version using docker compose and think everything should be installed correctly.

**Comment by NefixEstrada** [comment]
Hello!

This seems a weird error, since if you remove the file it should re-execute the whole wizard and, by extend, should recreate the whole DB.

Could you try to stopping all the containers (`docker-compose down`), remove the whole `/opt/isard` folder (you will lose all your IsardVDI data!) and bring up the whole thing again? If so, could you provide the whole log?

Also, where have you obtained the Docker images?

Thanks!

**Comment by jvinolas** [comment]
Check that this wizard path is mounted inside isard-webapp container. 
Also do remove wizard-disabled while isard is down, not while it is running.
The wizard should come again and no data will be lost as it will confirm that everything is already set up.

**Comment by sim6** [comment]
I'm closing this issue due to lack of feedback but, please, feel free to add more comments if you want more support.
